services:
  feishu-stub:
    build: .
    ports:
      - "8001:8001"
    environment:
      PYTHONPATH: /app/src
      PIP_INDEX_URL: https://mirrors.aliyun.com/pypi/simple/
      UV_DEFAULT_INDEX: https://mirrors.aliyun.com/pypi/simple/
      FEISHU_APP_ID:cli_a966c1b97a789ccc
      FEISHU_APP_SECRET:epF0rM8mtw0UxojoPGpLedKZYXCsp26b
      FEISHU_ENCRYPT_KEY:wekrjhnbcasieruji
      FEISHU_VERIFICATION_TOKEN:7HilU3PbY2GYick3dqJkgfONpdzgVrPi
    command: >
      uv run uvicorn orchestrator_kernel.entrypoints.feishu_stub:create_app
      --factory --host 0.0.0.0 --port 8001
