"""T039 — Task tree builder (US1 MVP: root_intent + single leaf_action).

`build_from_event()` turns an already-validated `EntryEvent` plus a list of
`LeafPlan` descriptors (what a future LLM planner would produce) into a
`TaskTree` of pydantic `Task` instances ready for the dispatcher.

Design decisions:
- IDs are **ULID**-based (26 chars) so they satisfy the 16..64 character
  constraint on `Task.taskId` / `traceId` and are lexicographically sortable
  for audit readability.
- `traceId` is supplied by the caller (produced earlier by the idempotency
  layer — T051). The builder refuses to invent one so the invariant
  "one traceId per (userId, eventId)" stays enforced in a single place.
- The builder returns a frozen-ish DTO (`TaskTree`) carrying root + leaves
  in a list; the kernel pipeline iterates `leaves` to drive dispatch. For
  MVP only single-leaf plans are supported, but the structure is already
  multi-leaf-ready so US6+ does not need a refactor.
- All Tasks start in `state="pending"` with no outcome / failureReason;
  state mutation happens exclusively through `kernel.state_machine.transition`.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any

import ulid

from ..contracts.budget import DEFAULT_BUDGET, Budget
from ..contracts.entry_event import EntryEvent
from ..contracts.task import RiskLevel, Task


@dataclass(frozen=True)
class LeafPlan:
    """One leaf_action descriptor produced by the planner (MVP: hand-fed).

    The `payload` is whatever the Worker ultimately receives verbatim; for
    `echo.say` the MVP contract is `{"text": str}`.
    """

    capability: str
    payload: dict[str, Any]
    risk_level: RiskLevel = "NORMAL"
    budget: Budget | None = None


@dataclass(frozen=True)
class TaskTree:
    """Build output. `root` plus the ordered list of leaves.

    `leaves` preserves the order of `LeafPlan`s passed in, which is also the
    order the dispatcher will walk for MVP (serial). Parallel dispatch is a
    later refactor and will keep this DTO stable.
    """

    root: Task
    leaves: list[Task] = field(default_factory=list)

    @property
    def all_tasks(self) -> tuple[Task, ...]:
        return (self.root, *self.leaves)


def _new_task_id() -> str:
    """Fresh ULID as a monotonic, sortable, 26-char task identifier."""
    return str(ulid.new().str)


def build_from_event(
    event: EntryEvent,
    *,
    trace_id: str,
    leaves: Sequence[LeafPlan],
    now: datetime | None = None,
) -> TaskTree:
    """Construct a root_intent + N leaf_action Task tree.

    Args:
        event: The validated EntryEvent this trace is rooted on. Its `text`
            is stored as `root.payload["text"]` for audit readability.
        trace_id: The idempotency-resolved traceId (16..64 chars). MUST be
            generated by the caller (T051 idempotency cache) and reused for
            replays.
        leaves: One or more `LeafPlan` entries. MVP tests pass exactly one.
        now: Optional clock override. Defaults to `datetime.now(UTC)`.

    Returns:
        A frozen `TaskTree`. All tasks are in state="pending" with no outcome.

    Raises:
        ValueError: If `leaves` is empty or any `LeafPlan.capability` is blank.
    """
    if not leaves:
        raise ValueError("build_from_event requires at least one leaf plan")

    created_at = now if now is not None else datetime.now(tz=UTC)
    root_task_id = _new_task_id()

    root = Task.model_validate(
        {
            "taskId": root_task_id,
            "parentTaskId": None,
            "traceId": trace_id,
            "kind": "root_intent",
            "state": "pending",
            "payload": {"text": event.text, "eventId": event.eventId},
            "createdAt": created_at,
        }
    )

    leaf_tasks: list[Task] = []
    for plan in leaves:
        if not plan.capability:
            raise ValueError("LeafPlan.capability MUST be non-empty")
        leaf_tasks.append(
            Task.model_validate(
                {
                    "taskId": _new_task_id(),
                    "parentTaskId": root_task_id,
                    "traceId": trace_id,
                    "kind": "leaf_action",
                    "capability": plan.capability,
                    "riskLevel": plan.risk_level,
                    "budget": (plan.budget or DEFAULT_BUDGET).model_dump(),
                    "state": "pending",
                    "payload": dict(plan.payload),
                    "createdAt": created_at,
                }
            )
        )

    return TaskTree(root=root, leaves=leaf_tasks)
